### PR TITLE
colour Jira Telco Priority field #212

### PR DESCRIPTION
**Pull request by npalchur**
adding the colors
 telco-priority-1 =red
telco-priority-2 =orange 
telco-priority-3 =color: blue 
telco-priority-4= black

### CODE REVIEW

**Review by adhil0 — CHANGES_REQUESTED** [review]
Nice work - only hangup is the linter error. You can solve it using `prettier`, which is available via the pre-commit yaml in our other PR: https://github.com/RHsyseng/t5g-field-support-team-utils/pull/282

@dcritch here's what it looks like:
image

**Comment by npalchur** [comment]
sure Aditya

**Comment by dcritch** [comment]
> Nice work - only hangup is the linter error. You can solve it using `prettier`, which is available via the pre-commit yaml in our other PR: #282
> 
> @dcritch here's what it looks like: image

looks good to me! the js linter isn't that descriptive, but seems like just one more nit before we can approve?

**Review by adhil0 — APPROVED** [review]

**Comment by dcritch** [comment]
thanks Naresh!

**Pull request merged**
