### PR TITLE
Add ability to generate fake data for Dev env's

### PR DESCRIPTION
**Pull request by adhil0**
- Use faker to generate fake data
- Inject fake data into cache if corresponding entry is empty of if `overwrite_cache` is `true`
- `fake_data`, `overwrite_cache`, and `number_of_cases` can be defined as env var's or via cli (`flask init-cache --fake-data --overwrite-cache --number-of-cases=123`)

One shortcoming is that multiple cases aren't created for accounts, ie every account only has one case. So we'll need to generate the accounts first, then generate multiple cases for each fake account. In any case, I figured I'd make a PR as a starting point.

TODO:
- [x] resolvedat and reliefat should be after createdate
- [x] Accounts should have multiple cases
- [x] Engineers should have multiple cases
- [x] fix linting issues

### CODE REVIEW

**Comment by adhil0** [comment]
@dcritch now we need to install the Faker package to run our tests. It's kind of big (2MB), let me know if you can see a way for us to avoid installing it.

**Comment by dcritch** [comment]
Are you concerned about the linter.yml or the install when firing up a dev env via docker-compose? For the workflow, I don't think we have much choice. For dev environments: is there a risk to having the package installed in prod?

**Comment by dcritch** [comment]
Yeah. How about using the package once to generate some data, then add them to the repo in a json file or something as a fixture?

**Comment by adhil0** [comment]
I think this is the best solution. Then we could add the code in the `bin` directory as a standalone cli.

**Comment by adhil0** [comment]
@dcritch Now dev env's will pull fake data from a JSON rather than generating it dynamically. I've also add the data generation code as a standalone CLI, so new fake data can be generated if desired. Faker has also been removed from our dependencies.

**Comment by dcritch** [comment]
nice, looks great! faker seems pretty neat! thanks for pulling this together. I'll merge, but we might want to include an doc update on using it as well

**Review by dcritch — APPROVED** [review]
:+1:

**Pull request merged**
