### PR TITLE
[wip] add by severity filter, remove watchlist and critsit filters

### PR DESCRIPTION
**Pull request by dcritch**

### CODE REVIEW

**Comment by adhil0** [comment]
The severity filter isn't working because we have HTML badges in that column, so it's having trouble parsing the text. Adding `{type: 'html', targets: 2}` under `columnDefs` in `table.js` fixes this, but then the column sorting stops working. I'm currently looking for a solution...

**Comment by dcritch** [comment]
ah bummer. thought it was a quick fix, saw the filter show up properly but didn't actually apply it to test :sob:

**Comment by adhil0** [comment]
@dcritch Sorting, permalinking, and filtering should all be working now

**Comment by dcritch** [comment]
sweet, looks great! thanks for taking care of it!

**Pull request closed without merging**
