### PR TITLE
Add colored badges for severity

### PR DESCRIPTION
**Pull request by adhil0**
- Fixed minor formatting issues
- Address #56 w/ colored badges:
Screenshot from 2022-02-23 15-58-08

### CODE REVIEW

**Comment by ptrnull** [comment]
@adhil0 Nice work! What about changing the font color to white and using a border-radius of for example 5px?

**Comment by adhil0** [comment]
@ptrnull Here's how it looks with white text + border radius of 5px. Also tweaked colors so that white text would appear better.
Screenshot from 2022-02-24 11-30-07

**Comment by dcritch** [comment]
lgtm! Let me know what you think @ptrnull and then I'll merge

**Pull request merged**
